alter table public.challenges
add column if not exists requires_photo boolean not null default false;

create table if not exists public.challenge_submissions (
    id bigint generated by default as identity primary key,
    profile_slug text not null references public.profiles(slug) on delete cascade,
    challenge_id bigint not null references public.challenges(id) on delete cascade,
    photo_path text not null,
    photo_filename text not null,
    photo_mime_type text,
    created_at timestamptz not null default timezone('utc', now()),
    unique(profile_slug, challenge_id)
);

create index if not exists idx_challenge_submissions_profile_slug
    on public.challenge_submissions(profile_slug);

create index if not exists idx_challenge_submissions_challenge_id
    on public.challenge_submissions(challenge_id);

insert into storage.buckets (id, name, public)
values ('challenge-proofs', 'challenge-proofs', false)
on conflict (id) do nothing;
